### ISSUE TITLE
Why don't you use global error handler? 

### ISSUE THREAD

**Issue by burdier** [Jadhielv/KCTest#26]
Hello guys, I hope you are doing well, I would like to recommend using a global error handler instead of catching things everywhere. 

here is a example: [handler]( https://jasonwatmore.com/post/2020/10/02/aspnet-core-31-global-error-handler-tutorial)

But if there is a reason for this approach, can you tell me what it is? 
https://github.com/Jadhielv/KCTest/blob/f4eef8b0581c24482439604ab066935c54d95b1f/Backend/src/KCTest.Application/Services/PermissionService.cs#L40

**Comment by Jadhielv** [comment]
@burdier if you have time please take a look at this issue.

**Comment by nminaya** [comment]
@Jadhielv I can help you with this

**Comment by Jadhielv** [comment]
Cool, you can take this one @nminaya 💪
