### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by nminaya** [Jadhielv/KCTest#30]
Running npm install command in the kctest-frontend folder throws the following error:

![image](https://user-images.githubusercontent.com/7952888/108796911-46cbbe80-7560-11eb-9d62-e5d5647a0066.png)

**Comment by Jadhielv** [comment]
Try deleting package-lock.json and reissuing npm install @nminaya

**Comment by nminaya** [comment]
@Jadhielv That fixes the issue
