### ISSUE TITLE
Services shouldn't return HttpResponse

### ISSUE THREAD

**Issue by nminaya** [Jadhielv/KCTest#7]
Services shouldn't return HttpResponses

https://github.com/Jadhielv/KCTest/blob/4b2d6219d03bd910d430fe54cffe5524caa2784b/Backend/src/KCTest.Domain/Services/IPermissionService.cs#L9

HttpResponses should be handled in the controller.

**Comment by Morzkat** [comment]
Should return a model like 
public class Response<T>
{
    string Message { get; set; }
    public int StatusCode { get; set; }
    public T Data { get; set; }
}
